// next-app/app/auth/signin/page.tsx
"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import axios from "axios";

export default function SignIn() {
  const router = useRouter();
  const [emailOrUsername, setEmailOrUsername] = useState<string>("");
  const [password, setPassword] = useState<string | number>();

  const submitHandler = async () => {
    const data = {
      email_username: emailOrUsername,
      password: password,
    };
    try {
      await axios
        .post("http://localhost:5000/auth/signin", data, {
          withCredentials: true,
        })
        .then(() => {
          setEmailOrUsername("");
          setPassword("");
          router.push("/home");
        });
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className="w-full md:w-10/12 lg:w-1/2  h-auto p-12 lg:px-32 bg-black rounded-2xl">
      <h2 className="font-bold text-3xl mb-4">Signin X</h2>
      <div>
        <input
          type="text"
          onChange={(e) => setEmailOrUsername(e.target.value)}
          value={emailOrUsername}
          className="border border-slate-200 outline-none p-4 h-12 w-full mb-6
           bg-black rounded-lg focus:border-sky-500"
          placeholder="Email or Username"
          required
        />
        <input
          type="password"
          onChange={(e) => setPassword(e.target.value)}
          className="border border-slate-200 outline-none p-4 h-12 w-full mb-6
           bg-black rounded-lg focus:border-sky-500"
          placeholder="Password"
          required
        />
        <button
          onClick={submitHandler}
          type="button"
          className="p-4 w-full rounded-2xl mb-2 text-center text-black bg-white"
        >
          Login
        </button>
        <p>
          don&apos;t have an account?{" "}
          <span className="text-sky-500">
            <Link href="/auth/signup">Signup</Link>
          </span>
        </p>
      </div>
    </div>
  );
}

// angular-app/src/app/features/signin/signin.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { AuthLayoutComponent } from '../../layouts/auth-layout/auth-layout.component';
import { AuthService } from '../../services/auth.service';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-signin',
  standalone: true,
  imports: [AuthLayoutComponent, FormsModule],
  templateUrl: './signin.component.html',
  styleUrl: './signin.component.css',
})
export class SigninComponent {
  constructor(private authService: AuthService, private router: Router) {}

  usernameOrEmail: string = '';
  password: string = '';

  submitSignin() {
    this.authService
      .login('http://localhost:5000/auth/signin', {
        email_username: this.usernameOrEmail,
        password: this.password,
      })
      .subscribe({
        next: (data: any) => {
          console.log(data);
          this.authService.setUser(data.user.id, data.user.username);
          this.router.navigate(['/']);
        },
        error: (error: any) => {
          console.log(error.message);
        },
      });
  }
}

<app-auth-layout>
  <div class="w-1/2 h-auto p-12 px-32 bg-black rounded-2xl">
    <h2 class="font-bold text-3xl mb-4">Signin X</h2>
    <div>
      <input
        type="text"
        class="border border-slate-200 outline-none p-4 h-12 w-full mb-6 bg-black rounded-lg focus:border-sky-500"
        placeholder="Email or Username"
        [(ngModel)]="usernameOrEmail"
        required
      />
      <input
        type="password"
        class="border border-slate-200 outline-none p-4 h-12 w-full mb-6 bg-black rounded-lg focus:border-sky-500"
        placeholder="Password"
        [(ngModel)]="password"
        required
      />
      <button
        type="button"
        (click)="submitSignin()"
        class="p-4 w-full rounded-2xl mb-2 text-center text-black bg-white"
      >
        Login
      </button>
      <p>
        don&apos;t have an account?
        <span class="text-sky-500">
          <a href="/signup">Signup</a>
        </span>
      </p>
    </div>
  </div>
</app-auth-layout>
