// next-app/components/Post.tsx
import { Dispatch, SetStateAction } from "react";
import { postType } from "@/types";
import axios from "axios";
import Link from "next/link";

import { BiMessageRounded, BiHeart, BiBookmark } from "react-icons/bi";
import { FaBookmark, FaTrash } from "react-icons/fa";
import { useRouter } from "next/navigation";
import { removeHashtag } from "@/utils";

export default function Post({
  post,
  user,
  posts,
  setIsModalComment,
  setPostId,
  setPosts,
  setPost,
}: {
  post?: postType;
  user?: { id: string; username: string } | null;
  posts?: postType[];
  setIsModalComment: Dispatch<SetStateAction<boolean>>;
  setPostId?: Dispatch<SetStateAction<string>>;
  setPosts?: Dispatch<SetStateAction<postType[]>>;
  setPost?: Dispatch<SetStateAction<postType>>;
}) {
  const router = useRouter();

  const likeHandler = async (
    e: React.MouseEvent<HTMLButtonElement>,
    post: postType
  ) => {
    try {
      const action = post.likedByCurrentUser ? "unlike" : "like";

      const res = await axios.post(
        "http://localhost:5000/feed/post/like",
        {
          postId: post._id,
          action: action,
        },
        {
          withCredentials: true,
        }
      );

      if (res.data === "ok") {
        const updatedPosts = posts?.map((p: postType): postType => {
          if (p._id === post._id) {
            return {
              ...p,
              likedByCurrentUser: action === "like",
              likesCount: (p.likesCount || 0) + (action === "like" ? 1 : -1),
            };
          }
          return p;
        });
        setPosts && setPosts(updatedPosts || []);
        setPost &&
          setPost((prevPost) => ({
            ...prevPost,
            likedByCurrentUser: action === "like",
            likesCount:
              (prevPost.likesCount || 0) + (action === "like" ? 1 : -1),
          }));
      }
    } catch (error) {
      console.log(error);
    }
  };

  const saveHandler = async (
    e: React.MouseEvent<HTMLButtonElement>,
    post: postType
  ) => {
    try {
      const action = post.savedByCurrentUser ? "unsave" : "save";

      const res = await axios.post(
        "http://localhost:5000/feed/post/save",
        {
          postId: post._id,
          action: action,
        },
        {
          withCredentials: true,
        }
      );
      if (res.data === "ok") {
        const updatedPosts = posts?.map((p: postType): postType => {
          if (p._id === post._id) {
            return {
              ...p,
              savedByCurrentUser: action === "save",
            };
          }
          return p;
        });
        setPosts && setPosts(updatedPosts || []);
        setPost &&
          setPost((prevPost) => ({
            ...prevPost,
            savedByCurrentUser: action === "save",
          }));
      }
    } catch (error) {
      console.log(error);
    }
  };

  const commentHandler = (postId: string) => {
    setIsModalComment((e) => !e);
    setPostId && setPostId(postId);
  };

  const deleteHandler = async (
    e: React.MouseEvent<HTMLButtonElement>,
    postId: string
  ) => {
    e.preventDefault();
    const cf = confirm("you want to delete this?");
    if (cf) {
      try {
        const respone = await axios.delete(
          `http://localhost:5000/feed/post/delete/${postId}`,
          {
            withCredentials: true,
          }
        );
        if (respone.data == "Post removed") {
          const updatedPosts = posts?.filter((p) => p._id != postId);
          setPosts && setPosts(updatedPosts || []);
          setPost && router.push("/home");
        } else {
          console.log(respone.data);
        }
      } catch (error) {
        console.log(error);
      }
    } else {
      return;
    }
  };

  return (
    <div className=" p-4 border-b border-slate-50 hover:bg-[#181818]">
      <div className="flex gap-2">
        <div className="avatar-sm"></div>

        <div className="flex-1">
          <Link href={`/home/${post?._id}`}>
            <div className="flex items-center justify-between">
              <Link href={`/home/profile/${post?.userId}`}>
                <h4 className="font-bold uppercase">
                  {post?.username || user?.username}
                </h4>
              </Link>

              {user?.id == post?.userId && (
                <button
                  type="button"
                  onClick={(e) => deleteHandler(e, post?._id || "")}
                  className="text-lg text-red-500 hover:text-red-700 mr-4"
                >
                  <FaTrash />
                </button>
              )}
            </div>
            <p>{post?.desc}</p>
            <div className="flex">
              {post?.tags?.map((tag, index) => (
                <Link
                  key={index}
                  href={`/home/tags/${removeHashtag(tag)}`}
                  className=" text-sky-500 font-bold mr-2"
                >
                  {tag}
                </Link>
              ))}
            </div>
          </Link>

          <div className="flex gap-2 mt-2 justify-between">
            <button
              onClick={() => commentHandler(post._id)}
              className="flex-center h-12  w-12 rounded-full hover:text-sky-500"
            >
              <BiMessageRounded className="text-2xl" />
            </button>
            <button
              onClick={(e) => likeHandler(e, post)}
              className={`flex-center h-12  w-12 rounded-full hover:text-red-700 ${
                post?.likedByCurrentUser && "text-red-500"
              }`}
            >
              <BiHeart className={`text-2xl  text-inherit`} />
              <span>{post?.likesCount || 0}</span>
            </button>
            <button
              onClick={(e) => saveHandler(e, post)}
              className="flex-center h-12  w-12 rounded-full hover:text-yellow-500"
            >
              {post?.savedByCurrentUser ? (
                <FaBookmark className="text-2xl text-yellow-500" />
              ) : (
                <BiBookmark className="text-2xl " />
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// angular-app/src/app/components/post/post.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { postType } from '../../types';
import { CommonModule } from '@angular/common';
import { FeedService } from '../../services/feed.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-post',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css',
})
export class PostComponent {
  constructor(private feedService: FeedService, private router: Router) {}
  @Input() post!: postType;
  @Input() posts!: postType[];
  @Input() user!: { userId: string; username: string };
  @Output() setIsModalCommentFn = new EventEmitter<boolean>();
  @Output() setPostIdFn = new EventEmitter<string>();
  @Output() setPostsFn = new EventEmitter<postType[]>();
  @Output() setPostFn = new EventEmitter<postType>();

  setIsModalComment(action: boolean) {
    this.setIsModalCommentFn.emit(action);
  }

  setPosts(updatedPosts: postType[]) {
    this.setPostsFn.emit(updatedPosts);
  }

  setPost(updatedPost: postType) {
    this.setPostFn.emit(updatedPost);
  }

  setPostId(postId: string) {
    this.setPostIdFn.emit(postId);
  }

  likeHandler(action: 'like' | 'unlike', post: postType) {
    this.feedService.likeActions(action, post).subscribe({
      next: (data: any) => {
        if (data == 'ok') {
          if (this.setPostsFn.observed) {
            const updatedPosts = this.posts.map((p) => {
              if (p._id === post._id) {
                return {
                  ...p,
                  likedByCurrentUser: action === 'like',
                  likesCount:
                    (p.likesCount || 0) + (action === 'like' ? 1 : -1),
                };
              }
              return p;
            });
            this.setPosts(updatedPosts);
          }
          if (this.setPostFn.observed) {
            const updatedPost = this.post;
            updatedPost.likedByCurrentUser = action === 'like';
            updatedPost.likesCount =
              (post.likesCount || 0) + (action === 'like' ? 1 : -1);
            this.setPost(updatedPost);
          }
        }
      },
      error: (error: Error) => {
        console.error(error);
      },
    });
  }

  saveHandler(action: 'save' | 'unsave', post: postType) {
    this.feedService.saveActions(action, post).subscribe({
      next: (data: any) => {
        if (data == 'ok') {
          if (this.setPostsFn.observed) {
            const updatedPosts = this.posts.map((p) => {
              if (p._id === post._id) {
                return {
                  ...p,
                  savedByCurrentUser: action === 'save',
                };
              }
              return p;
            });
            this.setPosts(updatedPosts);
          }
          if (this.setPostFn.observed) {
            const updatedPost = this.post;
            updatedPost.savedByCurrentUser = action === 'save';
            this.setPost(updatedPost);
          }
        }
      },
      error: (error: Error) => {
        console.log(error);
      },
    });
  }

  deleteHandler(event: MouseEvent, post: postType) {
    event.preventDefault();
    const cf = confirm('you want to delete this post?');
    if (cf)
      this.feedService.deleteActions(post).subscribe({
        next: (data: any) => {
          if (data == 'Post removed') {
            if (this.setPostsFn.observed) {
              const updatedPosts = this.posts.filter((p) => p._id != post._id);
              this.setPosts(updatedPosts);
            }
            this.router.navigate(['/']);
          }
        },
        error: (error: Error) => {
          console.log(error);
        },
      });
    return;
  }
}

<div class="p-4 border-b border-slate-50 hover:bg-[#181818]">
  <div class="flex gap-2">
    <div class="avatar-sm"></div>
    <div class="flex-1">
      <a [href]="'/post/' + post._id">
        <div class="flex items-center justify-between">
          <a [href]="'/profile/' + post.userId">
            <h4 class="font-bold uppercase">
              {{ post.username || user.username }}
            </h4>
          </a>
          @if(user.userId == post.userId){
          <button (click)="deleteHandler($event, post)">
            <i class="pi pi-trash" style="font-size: 1rem; color: red"></i>
          </button>

          }
        </div>
        <p>{{ post.desc }}</p>
        <div class="flex">
          <ng-container *ngFor="let tag of post.tags; let i = index">
            <a key="i" href="" class="text-sky-500 font-bold mr-2">
              {{ tag }}
            </a>
          </ng-container>
        </div>
      </a>

      <div class="flex gap-2 mt-2 justify-between">
        <button
          (click)="setIsModalComment(true); setPostId(post._id)"
          class="flex-center h-12 w-12 rounded-full hover:text-sky-500"
        >
          <i class="pi pi-comment" style="font-size: 1.5rem"></i>
        </button>
        <button
          (click)="
            likeHandler(post.likedByCurrentUser ? 'unlike' : 'like', post)
          "
          class="flex-center h-12 w-12 rounded-full hover:text-red-700"
        >
          @if (post.likedByCurrentUser) {
          <i class="pi pi-heart-fill" style="font-size: 1.5rem; color: red"></i>
          }@else{
          <i class="pi pi-heart" style="font-size: 1.5rem"></i>
          }
          <span class="mx-2">{{ post.likesCount }}</span>
        </button>
        <button
          (click)="
            saveHandler(post.savedByCurrentUser ? 'unsave' : 'save', post)
          "
          class="flex-center h-12 w-12 rounded-full hover:text-yellow-500"
        >
          @if (post.savedByCurrentUser) {
          <i
            class="pi pi-bookmark-fill"
            style="font-size: 1.5rem; color: yellow"
          ></i>
          }@else{
          <i class="pi pi-bookmark" style="font-size: 1.5rem"></i>
          }
        </button>
      </div>
    </div>
  </div>
</div>
